server:
  port: 8889
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer2:8889/eureka/
    fetch-registry: false
    register-with-eureka: false