server:
    port: 8888
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer1:8888/eureka/
    fetch-registry: false
    register-with-eureka: false