spring:
  application:
    name: cloud-goods
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Online_Retailers?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
  profiles: peer2
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update

server:
  port: 8890
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8888/eureka/